### ISSUE TITLE
What is everybody going to be working on?

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-code-sprint-2021-10#1]
Post a comment letting us know what you are going to be working on.

**Comment by rggibb** [comment]
**Target DGGS libraries:**
- [H3 library](https://github.com/uber/h3) from Uber
- [rHEALPix](https://github.com/manaakiwhenua/rhealpixdggs-py) from Manaaki Whenua - Landcare Research

Please reply to this comment nominating which libary you would like to work with and naming any additional DGGS libraries that you can bring to work on. We are especially interested if you have a 3D or 4D DGGS library.

**NB:** you can work with any DGGS library you have access to, there is no requirement for libraries used in sprints to be Open source.

**Comment by rggibb** [comment]
This is the first of a series of comments from me representing the OGC API DGGS standards team's suggestions for workstreams. These suggestions build on the current SwaggerHub document for [ogc-api-dggs](https://app.swaggerhub.com/apis/geofizzydrink/ogc_api_dggs/0.0.6/)
**Work Stream 1:**
1. implement OGC API Common i/f for target libraries.
2. implement OGC API DGGS Core i/f for target libraries.

A target library can be any DGGS library mentioned the [Target DGGS libraries comment](https://github.com/opengeospatial/ogcapi-code-sprint-2021-10/issues/1#issuecomment-947287391)

**Comment by rggibb** [comment]
**Work Stream 2:**
1. implement OGC API DGGS ZoneQuery i/f for target libraries.
- **Priority 1:** examples from each of \<\<set\>\>, \<\<query\>\> & \<\<reference\>\> to ensure that each of the patterns are tested,
- **Priority 2:** as many as possible of the rest of each type

**Comment by rggibb** [comment]
**Work Stream 3:**
The existing OGC API DGGS ZoneQuery i/f is defined for single zones, Surround Australia implemented these queries in rHEALPix for features, where each feature is represented by their list of zones. c.f. [rhealpix-sf](https://github.com/surroundaustralia/rhealpix-sf)
- **Priority 1:** Do these algorithms work for our other target DGGS libraries?
- **Priority 2:** Does the work in Priority 1 indicate new methods for OGC API DGGS ZoneQuery?
- **Priority 3:** What are the options for expressing feature lists in OGC API DGGS? Can we make an OGC API DGGS ZoneQuery pattern that is applicable to both single zones and features represented by lists of zones?
- **Priority 4:** Implement and test the new pattern for both single zones and features.

**Comment by allixender** [comment]
We have a functional but minimal Python implementation on the way for the YAML 0.0.6 DGGS, which we try to keep with while the spec doc is evolving:

- Git Hub: https://github.com/allixender/ogcapi-dggs-webdev-python
- Online Deploy: https://dggs-api-bozea3cspa-ew.a.run.app/dggs-api/

(get real H3 feature data: https://dggs-api-bozea3cspa-ew.a.run.app/dggs-api/collections/srtm_30m_estonia_h3/zones?resolution=3&limit=10 )

- there are currently two small datasets over Estonia (elevation and landuse, in H3 and RHEALPIX), however the API definition is not yet at the latest ...

- we are also aiming to showcase a web client that would load DGGS data from that service dynamically across zoom levels in the likes of the attached image:

![dggs-level-6](https://user-images.githubusercontent.com/4483885/138494416-5f2d335a-c7ff-4434-bd48-cf5bb0740035.png)

- we currently only have H3 javascript support, so Rhealpix can't be tested in the browser, but the RhealPix datasets can still be used test different client-interactions

**Comment by rggibb** [comment]
I've been giving some more thought to having a suite of simple standard DGGS datasets that could be used to test the OGC API DGGS. This might be needed to test Workstream 2 and 3 priorities, so I'll put it out there as a suggested activity

**Comment by allixender** [comment]
> 
> 
> I've been giving some more thought to having a suite of simple standard DGGS datasets that could be used to test the OGC API DGGS. This might be needed to test Workstream 2 and 3 priorities, so I'll put it out there as a suggested activity

@rggibb In the repository of our [Python DGGS API server](https://github.com/allixender/ogcapi-dggs-webdev-python/tree/main/misc) (see above) we have some H3 and rHealPix data in CSV and SQlite format. Maybe a starting point? Or do you mean even simpler, artificially constructed data that has a few cells in all the potential relationships to each other?

**Comment by rggibb** [comment]
> Or do you mean even simpler, artificially constructed data that has a few cells in all the potential relationships to each other?

@allixender yes .. that is what I was thinking, there are two cases:

1. single cells with each of the relationships - conceptually easy but I'm almost certaint it would have to be particular to each DGGS, as I cant think of a way to pose it completely generically
2. a set of simple features with their shapes represented in coords, with a defined process to convert it to a DGGS, do some simple processing to achieve representation at two or three different levels within the DGGS, and then do the topological tests at each level. My thinking here is that there may be some surprises if we want to guarantee that coordinate level relationships are either preserved in the DGGS or reveal some additional DGGS property that changes with level, but in a consistent way across different DGGS. I've got some ideas here, but haven't yet thought through all the ramifications.

**Comment by karriojala** [comment]
I will attempt to generate a Typescript client from the DGGS spec for our API client demo (https://github.com/opengeospatial/T17-API-D176-dev) and connect to the server that @allixender posted above.

If there are other DGGS server implementations can also try them out.

I could also look into API commons, does anyone know of a server implementation I could connect to?

In addition if anyone wants to use our WorldWind client in their own work I can help with that. We have a demo deployed here: https://ogctb17-apis-breithorn.solenix.ch/#/earth

**Comment by allixender** [comment]
@karriojala Thanks for the interest. I must warn you, the current implementation online at (my Google Cloud Function)[https://dggs-api-bozea3cspa-ew.a.run.app/dggs-api/ui] is developed against the one before the latest iteration of the spec, unfortunately also numbered [wip-ogc_api_dggs_zone_query_process_style 0.0.6](https://app.swaggerhub.com/apis/geofizzydrink/wip-ogc_api_dggs_zone_query_process_style/0.0.6)). The latest spec is supposedly here [ogc_api_dggs/0.0.6](https://app.swaggerhub.com/apis/geofizzydrink/ogc_api_dggs/0.0.6). I am currently refactoring and adjusting the thing, and I hope to commit a new version early tomorrow.

**Comment by recalcitrantsupplant** [comment]
I'll start an implementation of the [ogc-api-dggs](https://app.swaggerhub.com/apis/geofizzydrink/ogc_api_dggs/0.0.6/) for rhealpix

edit: an incomplete implementation is up here: https://ogc-api-dggs-rhealpix-qr4mrxboja-uc.a.run.app/
NB /docs provides the swagger UI

**Comment by recalcitrantsupplant** [comment]
Repo for API in previous comment is here https://github.com/surroundaustralia/ogc-api-dggs-rhealpix - happy to provide access if requested

**Comment by karriojala** [comment]
I have a simple client demo up here https://ogctb17-apis-breithorn.solenix.ch/#/earth 

Its using the DGGS server from @aaime. You can click on the zones to load child zones.

**Comment by rggibb** [comment]
@karriojala Interesting, with H3 because a parent's children don't cover the parent, sometimes when you click on a parent you dont get children where you actually clicked, so you cant just continue clicking in the same place to proceed through successive layers of children.
